// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace SGDPEDIDOS.Domain.Entities.StoreProcedure
{
    public partial class sp_view_week_menu_supplierResult
    {
        public string RESULTADO { get; set; }
    }
}
