// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace SGDPEDIDOS.Domain.Entities
{
    public partial class sp_week_menuResult
    {
        public string Result { get; set; }
    }
}
