// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SGDPEDIDOS.Domain.Entities.View;

public partial class VReportSupplierVm
{
    public int CompanyId { get; set; }

    public string CompanyIdentification { get; set; }

    public string CompanyName { get; set; }

    public string BrandName { get; set; }

    public string PhoneNumber { get; set; }

    public string Email { get; set; }

    public string FirstAddress { get; set; }

    public int InvoiceId { get; set; }

    public string ClienteEmpresa { get; set; }

    public DateTime InvoiceDate { get; set; }

    public decimal TotalAmount { get; set; }

    public DateTime? PaymentDueDate { get; set; }

    public decimal? PayrollDeduction { get; set; }

    public int TypeMenuId { get; set; }

    public string TypeMenuName { get; set; }

    public int MenuId { get; set; }

    public string Name { get; set; }

    public decimal Price { get; set; }

    public int Quantity { get; set; }

    public int UserId { get; set; }

    public string FirstName { get; set; }

    public string SecondName { get; set; }

    public string FirstLastName { get; set; }

    public string SecondLastName { get; set; }

    public string EmailUser { get; set; }

    public DateTime? DeletedDate { get; set; }

    public int OrderStatusId { get; set; }

    public string StatusName { get; set; }
}