// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SGDPEDIDOS.Api.Models;

public partial class VReportVm
{
    public int InvoiceId { get; set; }
    public DateTime InvoiceDate { get; set; }

    public decimal TotalAmount { get; set; }

    public int SupplierId { get; set; }

    public string SupplierName { get; set; }

    public int UserId { get; set; }

    public string UserName { get; set; }

    public string ProductName { get; set; }

    public decimal Price { get; set; }

    public int Quantity { get; set; }

    public string Details { get; set; }

    public string CompanyName { get; set; }

    public int CompanyId { get; set; }

    public int? DayCurrent { get; set; }
    public int OrderStatusId { get; set; }

    public string StatusName { get; set; }
    public string DeparmentName { get; set; }
}