// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SGDPEDIDOS.Domain.Entities.View;

public partial class VReportSupplier
{
    public int SupplierId { get; set; }

    public int SupplierTypeId { get; set; }

    public string SupplierIdentification { get; set; }

    public string SupplierName { get; set; }

    public string SupplierBrandName { get; set; }

    public string SupplierNumber { get; set; }

    public string SupplierEmail { get; set; }

    public string SupplierAddress { get; set; }

    public int ClientId { get; set; }

    public int ClientTypeId { get; set; }

    public string ClientIdentification { get; set; }

    public string ClientEmpresa { get; set; }

    public string ClientBrandName { get; set; }

    public string ClientNumber { get; set; }

    public string ClientEmail { get; set; }

    public string ClientAddress { get; set; }

    public int InvoiceId { get; set; }

    public DateTime InvoiceDate { get; set; }

    public decimal TotalAmount { get; set; }

    public DateTime? PaymentDueDate { get; set; }

    public decimal? PayrollDeduction { get; set; }

    public int TypeMenuId { get; set; }

    public string TypeMenuName { get; set; }

    public int MenuId { get; set; }

    public string Name { get; set; }

    public decimal Price { get; set; }

    public int Quantity { get; set; }

    public int UserId { get; set; }

    public string FirstName { get; set; }

    public string SecondName { get; set; }

    public string FirstLastName { get; set; }

    public string SecondLastName { get; set; }

    public string EmailUser { get; set; }

    public DateTime? DeletedDate { get; set; }

    public int OrderStatusId { get; set; }

    public string StatusName { get; set; }
}