// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SGDPEDIDOS.Domain.Entities.View;

public partial class VReportSuggestion
{
    public int TypeSuggestionId { get; set; }

    public string TypeSuggestionName { get; set; }

    public int SuggestionId { get; set; }

    public DateTime? SuggestionDate { get; set; }

    public string SuggestionComment { get; set; }

    public string OtherTypeSuggestion { get; set; }

    public bool IsActive { get; set; }

    public string CompanyName { get; set; }

    public int UserId { get; set; }

    public string FirstName { get; set; }

    public string SecondName { get; set; }

    public string FirstLastName { get; set; }

    public string SecondLastName { get; set; }

    public string Email { get; set; }

    public string CellPhoneNumber { get; set; }

    public int TypeMenuId { get; set; }

    public string TypeMenuName { get; set; }

    public int MenuId { get; set; }

    public string Name { get; set; }

    public string MenuDescription { get; set; }
}