// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SGDPEDIDOS.Domain.Entities
{
    public partial class Company
    {

        public Company()
        {
            InvoiceCompanies = new HashSet<Invoice>();
            InvoiceSuppliers = new HashSet<Invoice>();
            LogsCreditsBalances = new HashSet<LogsCreditsBalance>();
            Menus = new HashSet<Menu>();
            Suggestions = new HashSet<Suggestion>();
            SupplierCompanyCompanies = new HashSet<SupplierCompany>();
            SupplierCompanySuppliers = new HashSet<SupplierCompany>();
            Users = new HashSet<User>();
        }

        public int CompanyId { get; set; }
        public int TypeCompanyId { get; set; }
        public int TypeIdentificationId { get; set; }
        public string CompanyIdentification { get; set; }
        public string CompanyName { get; set; }
        public string BrandName { get; set; }
        public string FirstAddress { get; set; }
        public string SecondAddress { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string PostalCode { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public string MainContact { get; set; }
        public int MainContactTypeIdentificationId { get; set; }
        public string MainContactIdentification { get; set; }
        public string MainContactPhoneNumber { get; set; }
        public bool IsActive { get; set; }
        public DateTime? CreationDate { get; set; }
        public DateTime? DeletedDate { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? ModifiedDate { get; set; }
        public int? ModifiedBy { get; set; }

        public TimeSpan? StartServices { get; set; }
        public TimeSpan? EndServices { get; set; }

        public virtual TypesIdentification MainContactTypeIdentification { get; set; }
        public virtual TypesCompany TypeCompany { get; set; }
        public virtual TypesIdentification TypeIdentification { get; set; }
        public virtual ICollection<Invoice> InvoiceCompanies { get; set; }
        public virtual ICollection<Invoice> InvoiceSuppliers { get; set; }
        public virtual ICollection<LogsCreditsBalance> LogsCreditsBalances { get; set; }
        public virtual ICollection<Menu> Menus { get; set; }
        public virtual ICollection<Suggestion> Suggestions { get; set; }
        public virtual ICollection<SupplierCompany> SupplierCompanyCompanies { get; set; }
        public virtual ICollection<SupplierCompany> SupplierCompanySuppliers { get; set; }
        public virtual ICollection<User> Users { get; set; }
    }
}