// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SGDPEDIDOS.Domain.Entities;

public partial class Department
{
    public int DeparmentId { get; set; }

    public string DeparmentName { get; set; }

    public bool? IsActive { get; set; }
    public virtual ICollection<User> Users { get; set; } = new List<User>();
}