// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SGDPEDIDOS.Domain.Entities
{
    public partial class Favorite
    {
        public int FavoriteId { get; set; }
        public int UserId { get; set; }
        public int MenuId { get; set; }
        public bool? IsActive { get; set; }

        public virtual Menu Menu { get; set; }
        public virtual User User { get; set; }
    }
}