// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SGDPEDIDOS.Domain.Entities;

public partial class Image
{
    public int ImageId { get; set; }

    public int? MenuId { get; set; }

    public int? UserId { get; set; }

    public int? CompanyId { get; set; }

    public string CompanyCode { get; set; }

    public string ImageName { get; set; }

    public string ContentType { get; set; }

    public bool? IsActive { get; set; }

    public DateTime? CreationDate { get; set; }

    public int CreatedBy1 { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public int? ModifiedBy { get; set; }

    public DateTime? DeletedDate { get; set; }
}