// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace SGDPEDIDOS.Domain.Entities;

public partial class Invoice
{
    public Invoice()
    {
        InvoicesDetails = new HashSet<InvoicesDetail>();
        LogsCreditsBalances = new HashSet<LogsCreditsBalance>();
    }

    public int InvoiceId { get; set; }
    public int CompanyId { get; set; }
    public int SupplierId { get; set; }
    public int UserId { get; set; }
    public DateTime InvoiceDate { get; set; }
    public decimal TotalAmount { get; set; }
    public DateTime? PaymentDueDate { get; set; }
    public decimal? PayrollDeduction { get; set; }
    public DateTime? CreationDate { get; set; }
    public int CreatedBy { get; set; }
    public DateTime? ModifiedDate { get; set; }
    public int? ModifiedBy { get; set; }
    public DateTime? DeletedDate { get; set; }
    public int OrderStatusId { get; set; }

    [Timestamp]
    public byte[] RowVersion { get; set; }

    public virtual Company Company { get; set; }
    public virtual OrdersStatus OrderStatus { get; set; }
    public virtual Company Supplier { get; set; }
    public virtual User User { get; set; }
    public virtual ICollection<InvoicesDetail> InvoicesDetails { get; set; }
    public virtual ICollection<LogsCreditsBalance> LogsCreditsBalances { get; set; }
}
