// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SGDPEDIDOS.Domain.Entities
{
    public partial class LogsCreditsUser
    {
        public int LogCreditUserId { get; set; }
        public int UserId { get; set; }
        public decimal CreditBalance { get; set; }
        public decimal LimiteCreditPayroll { get; set; }
        public bool IsActive { get; set; }
        public DateTime CreationDate { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? ModifiedDate { get; set; }
        public int? ModifiedBy { get; set; }
        public DateTime? DeletedDate { get; set; }

        public virtual User User { get; set; }
    }
}