// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SGDPEDIDOS.Domain.Entities
{
    public partial class LogsCreditsBalance
    {
        public int LogCreditBalanceId { get; set; }
        public int CompanyId { get; set; }
        public int InvoiceId { get; set; }
        public int UserId { get; set; }
        public DateTime LogCreditBalanceDate { get; set; }
        public decimal CurrentBalance { get; set; }
        public decimal PreviousBalance { get; set; }
        public decimal ChargeApplied { get; set; }
        public decimal? PayrollDeduction { get; set; }
        public DateTime? CreationDate { get; set; }
        public int CreatedBy { get; set; }
        public DateTime? ModifiedDate { get; set; }
        public int? ModifiedBy { get; set; }
        public DateTime? DeletedDate { get; set; }

        public virtual Company Company { get; set; }
        public virtual Invoice Invoice { get; set; }
        public virtual User User { get; set; }
    }
}