// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SGDPEDIDOS.Domain.Entities
{
    public partial class Menu
    {
        public Menu()
        {
            Favorites = new HashSet<Favorite>();
            InvoicesDetails = new HashSet<InvoicesDetail>();
            Suggestions = new HashSet<Suggestion>();
            WeeklyMenusDetails = new HashSet<WeeklyMenusDetail>();
        }

        public int MenuId { get; set; }
        public int TypeMenuId { get; set; }
        public string Name { get; set; }
        public int CompanyId { get; set; }
        public string PictureOne { get; set; }
        public decimal MenuAmount { get; set; }
        public string MenuDescription { get; set; }
        public int QuantityAvailable { get; set; }
        public TimeSpan DeliveryTime { get; set; }
        public string PictureTwo { get; set; }
        public string PictureThree { get; set; }
        public bool? IsActive { get; set; }
        public DateTime? CreationDate { get; set; }
        public int CreatedBy { get; set; }
        public DateTime? ModifiedDate { get; set; }
        public int? ModifiedBy { get; set; }
        public DateTime? DeletedDate { get; set; }

        public virtual Company Company { get; set; }
        public virtual TypesMenu TypeMenu { get; set; }
        public virtual ICollection<Favorite> Favorites { get; set; }
        public virtual ICollection<InvoicesDetail> InvoicesDetails { get; set; }
        public virtual ICollection<Suggestion> Suggestions { get; set; }
        public virtual ICollection<WeeklyMenusDetail> WeeklyMenusDetails { get; set; }
    }
}