// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SGDPEDIDOS.Domain.Entities
{
    public partial class OrdersStatus
    {
        public OrdersStatus()
        {
            Invoices = new HashSet<Invoice>();
        }

        public int OrderStatusId { get; set; }
        public string StatusName { get; set; }
        public bool? IsActive { get; set; }

        public virtual ICollection<Invoice> Invoices { get; set; }
    }
}