// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SGDPEDIDOS.Domain.Entities
{
    public partial class RecoverKey
    {
        public int RecoveryId { get; set; }
        public int? UserId { get; set; }
        public string SecurityKey { get; set; }
        public DateTime? RequestDate { get; set; }
        public int? KeyExpirationDate { get; set; }
        public bool? Processed { get; set; }
        public bool? Expired { get; set; }

        public virtual User User { get; set; }
    }
}