// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SGDPEDIDOS.Domain.Entities
{
    public partial class TypesIdentification
    {
        public TypesIdentification()
        {
            CompanyMainContactTypeIdentifications = new HashSet<Company>();
            CompanyTypeIdentifications = new HashSet<Company>();
            Users = new HashSet<User>();
        }

        public int TypeIdentificationId { get; set; }
        public string TypeIdentificationName { get; set; }
        public bool? IsActive { get; set; }

        public virtual ICollection<Company> CompanyMainContactTypeIdentifications { get; set; }
        public virtual ICollection<Company> CompanyTypeIdentifications { get; set; }
        public virtual ICollection<User> Users { get; set; }
    }
}