// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SGDPEDIDOS.Domain.Entities
{
    public partial class TypesMenu
    {
        public TypesMenu()
        {
            Menus = new HashSet<Menu>();
        }

        public int TypeMenuId { get; set; }
        public string TypeMenuName { get; set; }
        public bool? IsActive { get; set; }

        public virtual ICollection<Menu> Menus { get; set; }
    }
}