// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SGDPEDIDOS.Domain.Entities
{
    public partial class TypeSuggestion
    {
        public TypeSuggestion()
        {
            Suggestions = new HashSet<Suggestion>();
        }

        public int TypeSuggestionId { get; set; }
        public string TypeSuggestionName { get; set; }
        public bool? IsActive { get; set; }
        public bool IsOther { get; set; }

        public virtual ICollection<Suggestion> Suggestions { get; set; }
    }
}