// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SGDPEDIDOS.Domain.Entities
{
    public partial class TypesCompany
    {
        public TypesCompany()
        {
            Companies = new HashSet<Company>();
        }

        public int TypeCompanyId { get; set; }
        public string TypeCompanyName { get; set; }
        public bool? IsActive { get; set; }

        public virtual ICollection<Company> Companies { get; set; }
    }
}