// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SGDPEDIDOS.Domain.Entities
{
    public partial class WeeklyMenu
    {
        public WeeklyMenu()
        {
            WeeklyMenusDetails = new HashSet<WeeklyMenusDetail>();
        }

        public int WeeklyMenusId { get; set; }
        public DateTime WeeklyFrom { get; set; }
        public DateTime WeeklyTo { get; set; }
        public bool? IsActive { get; set; }

        public virtual ICollection<WeeklyMenusDetail> WeeklyMenusDetails { get; set; }
    }
}