// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SGDPEDIDOS.Domain.Entities
{
    public partial class WeeklyMenusDetail
    {
        public int WeeklyMenusDetailsId { get; set; }
        public int WeeklyMenusId { get; set; }
        public int WeeklyDay { get; set; }
        public int MenuId { get; set; }
        public bool? IsActive { get; set; }

        public virtual Menu Menu { get; set; }
        public virtual WeeklyDay WeeklyDayNavigation { get; set; }
        public virtual WeeklyMenu WeeklyMenus { get; set; }
    }
}